data:
  train_list: "/root/HiFiVFS/data/vox2_curated_train.txt"
  vae_latent: true
  image_size_for_vae: [640, 640]  # 修改为640x640
  target_img_size: [640, 640]     # 同步修改目标尺寸
  num_frames: 2

model:
  frid_channels: 1280
  allow_frid_projection: true

training:
  batch_size: 1
  num_epochs: 100
  learning_rate: 0.00002
  beta1: 0.5
  beta2: 0.999
  
  loss_weights:
    reconstruction: 10.0
    attribute: 10.0
    identity: 0.5  # 降低身份损失权重
    adversarial: 1.0
    
  save_interval: 1
  log_interval: 5
  
  checkpoint_dir: "/root/HiFiVFS/checkpoints/vox2_640"
  sample_dir: "/root/HiFiVFS/samples/vox2_640"